---
title: "General Workflow BD ETMUN"
author: "Paul Gourdon"
date: "23/10/2019"
output: html_document
---
# Data Description and sources

The ETMUN Database allows a Europe-wide approach to Transnational Municipal Networks.

Most of the data come from a search of the 2015 Yearbook of International Organizatons provided by the Union of International Associations ([UIA KEEP](https://uia.org/)), an NGO based in Brussels. The other organizations come from an internet watch. 

Once the various transnational organisations bringing together urban governments have been registered in the ETMUN database, the member cities of each organisation are manually collected (mainly on the websites of the associations).

Each time, the full name of the member entity (municipality, intermunicipality, or sometimes association, company, administration) is registered, to which a abbreviated name (name of the simplified city, or name of the city in which the entity has its headquarters) is attached.

 
"ETMUN Organization files" contains all information about each Transnational Municipal Network.
"ETMUN Member cities" contains all the different member cities and the name of the associaton(s) in which they are involved. 


# Main Goals

- To perform a locational analysis of the density of adhesions to Transnational Municipal Network.

- To aggregate the different member entity into the urban areas to which they belong and have only one entry per city with the number of memberships.

- To look for hierarchical structure regarding level of involvment in such organization : urban concentration, differenciation between countries, regions and cities. To test rank-size hypotheses.


## Main steps needed

- (1) Geocode all entities 
- (2) Aggregate data : make a list of unique member cities
- (3) Correct error in geocoding
- (4) First analysis of density (grid) with all Partners and lead Partners (and first with all involments)
- (5) Spatial Joint with Urban Areas (UMZ database)
- (6) Find a solution for entity outside urban areas (get an administrative population for example, or just filter the sample)
- (7) Map aggregate participation at the urban areas level. and performe rank-size analysis (with participations and number of partners in Urban areas)
- (8) Recognise Urban Governement and cities in the list of partner
- (9) Filter the dataset to keep only projects that involved a majority of cities.
- (10) Perform locational analysis on the filtered dataset

## Steps

### (1) Geocode :
- Problem encodage, reading UTF-8 (windows issues described here [escaping-character-encoding-hell-r-windows](https://dss.iq.harvard.edu/blog/escaping-character-encoding-hell-r-windows))
- Clean and concatenate location data to get a full address for each partner
- Find solution for geocoding : photon too fuzzy. ggmap with account to Google geocoding API.
- Merge geocode result to the Partners dataframe. Check the missing address and do manual geocoding
- Create single ID for participation (n = 30 000) and single ID for partners
- Check info about countries and see geocoding errors (mapping different sample with map view )

---



Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
VOiture de courses
